# Generated by Django 4.2.27 on 2025-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
