# Generated by Django 4.2.27 on 2025-12-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_currency_order_items_payment_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="external_id",
            new_name="order_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="external_id",
            new_name="payment_id",
        ),
    ]
