# Generated by Django 4.2.27 on 2025-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_webhookendpoint_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order.created", "Order Created"),
                    ("payment.succeeded", "Payment Succeeded"),
                    ("payment.failed", "Payment Failed"),
                    ("payment.refunded", "Payment Refunded"),
                    ("payment.chargeback", "Chargeback"),
                ],
                max_length=50,
            ),
        ),
    ]
