# Generated by Django 4.2.27 on 2025-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_alter_webhookevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("order.created", "Order Created"),
                    ("payment.succeeded", "Payment Succeeded"),
                    ("payment.failed", "Payment Failed"),
                    ("payment.refunded", "Payment Refunded"),
                    ("payment.chargeback", "Chargeback"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
