# Generated by Django 4.2.27 on 2025-12-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0005_alter_webhookevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("order.created", "Order Created"),
                    ("order.updated", "Order Updated"),
                    ("order.cancelled", "Order Cancelled"),
                    ("payment.succeeded", "Payment Succeeded"),
                    ("payment.failed", "Payment Failed"),
                    ("payment.refunded", "Payment Refunded"),
                    ("payment.chargeback", "Payment Chargeback"),
                ],
                max_length=50,
            ),
        ),
    ]
