# Generated by Django 4.2.27 on 2025-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_alter_webhookevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooklog",
            name="request_headers",
            field=models.JSONField(
                blank=True, default=dict, help_text="Headers sent or received"
            ),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="response_body",
            field=models.TextField(
                blank=True, help_text="Response body from the destination"
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="message",
            field=models.TextField(blank=True, help_text="Human readable summary"),
        ),
    ]
